# Generated by Django 5.1.3 on 2024-11-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulgThoughtsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulgthoughtregistration',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bulgthoughtregistration',
            old_name='Conatct',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='bulgthoughtregistration',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='bulgthoughtregistration',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='bulgthoughtregistration',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='bulgthoughtregistration',
            old_name='Password',
            new_name='password',
        ),
    ]
